### PR TITLE
Add Oreo 8.0 / 8.1 jar

### PR DESCRIPTION
**Pull request by Trumeet**
# Add Oreo 8.0 / 8.1 jar
I have just compiled the Android 8.0.0 r34 and android 8.1.0_r14 code, while helping this project to add Android 8.0.0 and 8.1.0 android.jar :)
I also added `Telephony`, `Common` to `android.jar`, then add optional `services.jar`.

### CODE REVIEW

**Comment by luongvo** [comment]
Wow, i want this now, tks 👏

**Comment by Tornaco** [comment]
Thanks, I want to use it:)

**Comment by Trumeet** [comment]
~~Lazy @anggrayudi still not merge it.....~~

**Comment by Tornaco** [comment]
Hey, what does service.jar used for?
I've tested the lastest version of android.jar you uploaded@c2172544f29a72789820078128d394f852827acf, 
there is some string res missing, such as
``` R.string.keyboard_headset_required_to_hear_password```

Thanks.

**Comment by Trumeet** [comment]
You need read readme, service.jar provides System Server classes.
I forgot add resources to android.jar, you can follow project's readme to get resources.

**Comment by geecko86** [comment]
@Trumeet Any plans to release 27?

**Comment by Trumeet** [comment]
Now Android 27 is now available 😄

**Pull request merged**
